### ISSUE TITLE
Problem with POST to create calculated metrics: 4-topSqlStatements.json

### ISSUE THREAD

**Issue by Stiuzz** [Dynatrace-Asad-Ali/PTC-Windchill#2]
Probably due to some changes in Dynatrace's API the placeholder {Database-Statement} for DB statement is no longer available (I'm not sure but I think that was simply replaced by {Request:Name}) so the POST to create the calculated metric return a 400 error.

Regards
Stiuzz

**Comment by Dynatrace-Asad-Ali** [comment]
This issue is resolved in the latest version.
